// Zentrale Länderliste: englischer Name (wie in der Karten-Geometrie) → deutsch.
// Wird von der Weltkarte UND vom Admin-Dropdown genutzt, damit beide konsistent sind.
export const COUNTRY_EN_DE = {
  'Afghanistan': 'Afghanistan',
  'Albania': 'Albanien',
  'Algeria': 'Algerien',
  'Angola': 'Angola',
  'Argentina': 'Argentinien',
  'Armenia': 'Armenien',
  'Australia': 'Australien',
  'Austria': 'Österreich',
  'Azerbaijan': 'Aserbaidschan',
  'Bahamas': 'Bahamas',
  'Bangladesh': 'Bangladesch',
  'Belarus': 'Belarus',
  'Belgium': 'Belgien',
  'Belize': 'Belize',
  'Benin': 'Benin',
  'Bhutan': 'Bhutan',
  'Bolivia': 'Bolivien',
  'Bosnia and Herz.': 'Bosnien und Herzegowina',
  'Botswana': 'Botswana',
  'Brazil': 'Brasilien',
  'Brunei': 'Brunei',
  'Bulgaria': 'Bulgarien',
  'Burkina Faso': 'Burkina Faso',
  'Burundi': 'Burundi',
  'Cambodia': 'Kambodscha',
  'Cameroon': 'Kamerun',
  'Canada': 'Kanada',
  'Central African Rep.': 'Zentralafrikanische Republik',
  'Chad': 'Tschad',
  'Chile': 'Chile',
  'China': 'China',
  'Colombia': 'Kolumbien',
  'Congo': 'Kongo',
  'Costa Rica': 'Costa Rica',
  'Croatia': 'Kroatien',
  'Cuba': 'Kuba',
  'Cyprus': 'Zypern',
  'Czechia': 'Tschechien',
  'Dem. Rep. Congo': 'Demokratische Republik Kongo',
  'Denmark': 'Dänemark',
  'Djibouti': 'Dschibuti',
  'Dominican Rep.': 'Dominikanische Republik',
  'Ecuador': 'Ecuador',
  'Egypt': 'Ägypten',
  'El Salvador': 'El Salvador',
  'Eq. Guinea': 'Äquatorialguinea',
  'Eritrea': 'Eritrea',
  'Estonia': 'Estland',
  'Ethiopia': 'Äthiopien',
  'Fiji': 'Fidschi',
  'Finland': 'Finnland',
  'France': 'Frankreich',
  'Gabon': 'Gabun',
  'Gambia': 'Gambia',
  'Georgia': 'Georgien',
  'Germany': 'Deutschland',
  'Ghana': 'Ghana',
  'Greece': 'Griechenland',
  'Greenland': 'Grönland',
  'Guatemala': 'Guatemala',
  'Guinea': 'Guinea',
  'Guinea-Bissau': 'Guinea-Bissau',
  'Guyana': 'Guyana',
  'Haiti': 'Haiti',
  'Honduras': 'Honduras',
  'Hungary': 'Ungarn',
  'Iceland': 'Island',
  'India': 'Indien',
  'Indonesia': 'Indonesien',
  'Iran': 'Iran',
  'Iraq': 'Irak',
  'Ireland': 'Irland',
  'Israel': 'Israel',
  'Italy': 'Italien',
  'Ivory Coast': 'Elfenbeinküste',
  'Jamaica': 'Jamaika',
  'Japan': 'Japan',
  'Jordan': 'Jordanien',
  'Kazakhstan': 'Kasachstan',
  'Kenya': 'Kenia',
  'Kosovo': 'Kosovo',
  'Kuwait': 'Kuwait',
  'Kyrgyzstan': 'Kirgisistan',
  'Laos': 'Laos',
  'Latvia': 'Lettland',
  'Lebanon': 'Libanon',
  'Lesotho': 'Lesotho',
  'Liberia': 'Liberia',
  'Libya': 'Libyen',
  'Lithuania': 'Litauen',
  'Luxembourg': 'Luxemburg',
  'Madagascar': 'Madagaskar',
  'Malawi': 'Malawi',
  'Malaysia': 'Malaysia',
  'Mali': 'Mali',
  'Mauritania': 'Mauretanien',
  'Mexico': 'Mexiko',
  'Moldova': 'Moldau',
  'Mongolia': 'Mongolei',
  'Montenegro': 'Montenegro',
  'Morocco': 'Marokko',
  'Mozambique': 'Mosambik',
  'Myanmar': 'Myanmar',
  'Namibia': 'Namibia',
  'Nepal': 'Nepal',
  'Netherlands': 'Niederlande',
  'New Caledonia': 'Neukaledonien',
  'New Zealand': 'Neuseeland',
  'Nicaragua': 'Nicaragua',
  'Niger': 'Niger',
  'Nigeria': 'Nigeria',
  'North Korea': 'Nordkorea',
  'North Macedonia': 'Nordmazedonien',
  'Norway': 'Norwegen',
  'Oman': 'Oman',
  'Pakistan': 'Pakistan',
  'Panama': 'Panama',
  'Papua New Guinea': 'Papua-Neuguinea',
  'Paraguay': 'Paraguay',
  'Peru': 'Peru',
  'Philippines': 'Philippinen',
  'Poland': 'Polen',
  'Portugal': 'Portugal',
  'Puerto Rico': 'Puerto Rico',
  'Qatar': 'Katar',
  'Romania': 'Rumänien',
  'Russia': 'Russland',
  'Rwanda': 'Ruanda',
  'Saudi Arabia': 'Saudi-Arabien',
  'Senegal': 'Senegal',
  'Serbia': 'Serbien',
  'Sierra Leone': 'Sierra Leone',
  'Singapore': 'Singapur',
  'Slovakia': 'Slowakei',
  'Slovenia': 'Slowenien',
  'Solomon Is.': 'Salomonen',
  'Somalia': 'Somalia',
  'South Africa': 'Südafrika',
  'South Korea': 'Südkorea',
  'South Sudan': 'Südsudan',
  'Spain': 'Spanien',
  'Sri Lanka': 'Sri Lanka',
  'Sudan': 'Sudan',
  'Suriname': 'Suriname',
  'Sweden': 'Schweden',
  'Switzerland': 'Schweiz',
  'Syria': 'Syrien',
  'Taiwan': 'Taiwan',
  'Tajikistan': 'Tadschikistan',
  'Tanzania': 'Tansania',
  'Thailand': 'Thailand',
  'Timor-Leste': 'Osttimor',
  'Togo': 'Togo',
  'Trinidad and Tobago': 'Trinidad und Tobago',
  'Tunisia': 'Tunesien',
  'Turkey': 'Türkei',
  'Turkmenistan': 'Turkmenistan',
  'Uganda': 'Uganda',
  'Ukraine': 'Ukraine',
  'United Arab Emirates': 'Vereinigte Arabische Emirate',
  'United Kingdom': 'Vereinigtes Königreich',
  'United States of America': 'Vereinigte Staaten',
  'Uruguay': 'Uruguay',
  'Uzbekistan': 'Usbekistan',
  'Vanuatu': 'Vanuatu',
  'Venezuela': 'Venezuela',
  'Vietnam': 'Vietnam',
  'Yemen': 'Jemen',
  'Zambia': 'Sambia',
  'Zimbabwe': 'Simbabwe',
};

// Optionen fürs Dropdown, alphabetisch nach deutschem Namen sortiert.
// Jede Option: [wert, anzeige]. Der Wert ist der deutsche Name (so wie er
// in origin_country gespeichert wird und von der Weltkarte verstanden wird).
export const COUNTRY_OPTIONS = Object.values(COUNTRY_EN_DE)
  .sort((a, b) => a.localeCompare(b, 'de'))
  .map((de) => [de, de]);